### ISSUE TITLE
Additional option property that will be passed to toc.insert

### ISSUE THREAD

**Issue by lakakucharita** [jonschlinkert/gulp-markdown-toc#1]
Version: 0.1.0

I'm currently using `gulp-markdown-toc` in a build process I'm implementing to convert MD files to HTML. Unfortunately, the markers (`<!-- toc -->` and `<!-- tocstop -->`) are not encoded properly and are displayed as is in the HTML output. I ended up using `gulp-replace` to remove these markers before proceeding with the conversion. 

I've checked `markdown-toc` and `toc.insert` has a 2nd argument to configure the markers. I was wondering if in the next version, you can add a property in `gulp-markdown-toc`'s options which will then be passed to `toc.insert`. Thank you!

**Comment by jonschlinkert** [comment]
sorry for the delay!
